version: '3'
services:
  webapp:
    build:
      context: ./
      args:
        PORT: $PORT
    image: mesquillanet:$RELEASE
    container_name: mesquillanet
    restart: always
    ports:
      - "$PORT"
    volumes:
      - /disk2/mesquillanet:/var/local/mesquillanet
    env_file: .env
    environment:
      - VIRTUAL_HOST=mesquilla.net,www.mesquilla.net,mesquillanet-local.net

networks:
  default:
    external:
      name: nginx-proxy
